### ISSUE TITLE
is there an option to get the production of the day

### ISSUE THREAD

**Issue by Schmandre** [mawoka-myblock/apsystemsapi-ha#2]
Hello,

I want to use it also for my energy dashboard in home assistant. Here I would need the production of the day, and not the all time production. 

![image](https://github.com/mawoka-myblock/apsystemsapi-ha/assets/47451170/93ccfd5b-b7e2-4487-93d3-f1528cffe10a)

I would like to add it by myself, but couldn't find any API documentation. So is there a way to add that?

BR
Schmandre

**Comment by mawoka-myblock** [comment]
Try to add it under solar like I did (ignore the warning)
![Screenshot_20231114-095053_Home Assistant](https://github.com/mawoka-myblock/apsystemsapi-ha/assets/66328166/6d84f310-cbd4-4d23-9b1b-61651c0907e4)

**Comment by Schmandre** [comment]
Perfect, was a bit confused cause the sensor is called "all the time" but I just wanted to know it at the moment. 

So the energy dashboard works much smarter than my brain. Worked for me. Thank you again ;)
