### ISSUE TITLE
Display two DC-inputs

### ISSUE THREAD

**Issue by I-B-H** [mawoka-myblock/apsystemsapi-ha#4]
Is it possible to display the two DC-inputs separately? In the new App-Version I can see the input of panel 1 and 2.

Regards

**Comment by mawoka-myblock** [comment]
Hey, good idea, but as I am only using the local integration, I won't be able to work on new features as it'd be a hassle to get the inverter back into the cloud and so on. Sorry for that. I'm also gonna archive this repo.
